apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-basic-1777291443827
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/test-image:fb95fb105ca310b92089f77750b2927b6955a6ee
          name: container-image
